# docker/nginx/Dockerfile.prod
FROM node:20 AS frontend-build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=frontend-build /app/dist /var/www/frontend
COPY docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
